export const itemTypes = {
  ITEM_WAIT_CHANGES: 'ITEM_WAIT_CHANGES',
  ITEM_ADD: 'ITEM_ADD',
  ITEM_DELETE: 'ITEM_DELETE',
  ITEM_CHANGE: 'ITEM_CHANGE',
  ITEM_DATA_ERROR: 'ITEM_DATA_ERROR',
  ITEM_SERVER_ERROR: 'ITEM_SERVER_ERROR'
}